"""initial_schema

Revision ID: 3d4fe931a43a
Revises: 
Create Date: 2025-10-14 22:26:56.390894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '3d4fe931a43a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable required PostgreSQL extensions
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribution_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.String(length=36), nullable=False),
    sa.Column('blockchain_tx_hash', sa.String(length=128), nullable=True),
    sa.Column('blockchain_address', sa.String(length=128), nullable=True),
    sa.Column('attribution_type', sa.String(length=50), nullable=True),
    sa.Column('proof_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attribution_records_blockchain', 'attribution_records', ['blockchain_tx_hash'], unique=False)
    op.create_index('idx_attribution_records_media', 'attribution_records', ['media_id', 'created_at'], unique=False)
    op.create_table('audio_fingerprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fp_hash', sa.String(length=128), nullable=False),
    sa.Column('media_id', sa.String(length=36), nullable=False),
    sa.Column('offset_seconds', sa.Float(), nullable=True),
    sa.Column('fingerprint_data', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audio_fingerprints_created_at', 'audio_fingerprints', ['created_at'], unique=False)
    op.create_index('idx_audio_fingerprints_hash', 'audio_fingerprints', ['fp_hash'], unique=False)
    op.create_index('idx_audio_fingerprints_media_id', 'audio_fingerprints', ['media_id', 'offset_seconds'], unique=False)
    op.create_table('image_hashes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.String(length=36), nullable=False),
    sa.Column('dhash', sa.String(length=64), nullable=True),
    sa.Column('phash', sa.String(length=64), nullable=True),
    sa.Column('ahash', sa.String(length=64), nullable=True),
    sa.Column('dhash_16', sa.String(length=256), nullable=True),
    sa.Column('phash_16', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id')
    )
    op.create_index('idx_image_hashes_dhash', 'image_hashes', ['dhash'], unique=False)
    op.create_index('idx_image_hashes_media_id', 'image_hashes', ['media_id'], unique=False)
    op.create_index('idx_image_hashes_phash', 'image_hashes', ['phash'], unique=False)
    op.create_table('media_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_media_embeddings_kind', 'media_embeddings', ['kind'], unique=False)
    op.create_index('idx_media_embeddings_media_id', 'media_embeddings', ['media_id'], unique=False)
    op.create_index('idx_media_embeddings_uploaded_at', 'media_embeddings', ['uploaded_at'], unique=False)
    op.create_table('media_files',
    sa.Column('media_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('storage_uri', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.String(length=128), nullable=True),
    sa.Column('upload_user_id', sa.String(length=36), nullable=True),
    sa.Column('upload_ip', postgresql.INET(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('processing_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('media_id')
    )
    op.create_index('idx_media_files_created_at', 'media_files', ['created_at'], unique=False)
    op.create_index('idx_media_files_hash', 'media_files', ['file_hash'], unique=False)
    op.create_index('idx_media_files_status', 'media_files', ['status'], unique=False)
    op.create_table('similarity_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_media_id', sa.String(length=36), nullable=False),
    sa.Column('match_media_id', sa.String(length=36), nullable=False),
    sa.Column('match_type', sa.String(length=50), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('match_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_similarity_matches_query_media', 'similarity_matches', ['query_media_id', 'created_at'], unique=False)
    op.create_index('idx_similarity_matches_score', 'similarity_matches', ['similarity_score'], unique=False)
    op.create_index('idx_similarity_matches_type_score', 'similarity_matches', ['match_type', 'similarity_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_similarity_matches_type_score', table_name='similarity_matches')
    op.drop_index('idx_similarity_matches_score', table_name='similarity_matches')
    op.drop_index('idx_similarity_matches_query_media', table_name='similarity_matches')
    op.drop_table('similarity_matches')
    op.drop_index('idx_media_files_status', table_name='media_files')
    op.drop_index('idx_media_files_hash', table_name='media_files')
    op.drop_index('idx_media_files_created_at', table_name='media_files')
    op.drop_table('media_files')
    op.drop_index('idx_media_embeddings_uploaded_at', table_name='media_embeddings')
    op.drop_index('idx_media_embeddings_media_id', table_name='media_embeddings')
    op.drop_index('idx_media_embeddings_kind', table_name='media_embeddings')
    op.drop_table('media_embeddings')
    op.drop_index('idx_image_hashes_phash', table_name='image_hashes')
    op.drop_index('idx_image_hashes_media_id', table_name='image_hashes')
    op.drop_index('idx_image_hashes_dhash', table_name='image_hashes')
    op.drop_table('image_hashes')
    op.drop_index('idx_audio_fingerprints_media_id', table_name='audio_fingerprints')
    op.drop_index('idx_audio_fingerprints_hash', table_name='audio_fingerprints')
    op.drop_index('idx_audio_fingerprints_created_at', table_name='audio_fingerprints')
    op.drop_table('audio_fingerprints')
    op.drop_index('idx_attribution_records_media', table_name='attribution_records')
    op.drop_index('idx_attribution_records_blockchain', table_name='attribution_records')
    op.drop_table('attribution_records')
    # ### end Alembic commands ###
