"""add_missing_columns_to_matches_and_attribution

Revision ID: b5afe644c2ee
Revises: 3ada2742f49d
Create Date: 2025-10-14 23:02:48.522819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5afe644c2ee'
down_revision: Union[str, None] = '3ada2742f49d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribution_records', sa.Column('file_hash', sa.String(length=128), nullable=True))
    op.add_column('attribution_records', sa.Column('media_type', sa.String(length=20), nullable=True))
    op.add_column('attribution_records', sa.Column('matches_found', sa.Integer(), nullable=True))
    op.add_column('attribution_records', sa.Column('high_confidence_matches', sa.Integer(), nullable=True))
    op.add_column('attribution_records', sa.Column('max_similarity_score', sa.Float(), nullable=True))
    op.add_column('attribution_records', sa.Column('processing_time_ms', sa.Float(), nullable=True))
    op.drop_index(op.f('idx_media_embeddings_vector_hnsw'), table_name='media_embeddings', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.add_column('similarity_matches', sa.Column('match_category', sa.String(length=50), nullable=True))
    op.add_column('similarity_matches', sa.Column('embedding_type', sa.String(length=50), nullable=True))
    op.add_column('similarity_matches', sa.Column('fingerprint_hash', sa.String(length=128), nullable=True))
    op.add_column('similarity_matches', sa.Column('offset_seconds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('similarity_matches', 'offset_seconds')
    op.drop_column('similarity_matches', 'fingerprint_hash')
    op.drop_column('similarity_matches', 'embedding_type')
    op.drop_column('similarity_matches', 'match_category')
    op.create_index(op.f('idx_media_embeddings_vector_hnsw'), 'media_embeddings', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_column('attribution_records', 'processing_time_ms')
    op.drop_column('attribution_records', 'max_similarity_score')
    op.drop_column('attribution_records', 'high_confidence_matches')
    op.drop_column('attribution_records', 'matches_found')
    op.drop_column('attribution_records', 'media_type')
    op.drop_column('attribution_records', 'file_hash')
    # ### end Alembic commands ###
