"""add_columns_to_media_files

Revision ID: ce3d214088e3
Revises: b5afe644c2ee
Create Date: 2025-10-14 23:06:46.235708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce3d214088e3'
down_revision: Union[str, None] = 'b5afe644c2ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_media_embeddings_vector_hnsw"),
        table_name="media_embeddings",
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
        if_exists=True,
    )
    op.add_column('media_files', sa.Column('matches_found', sa.Integer(), nullable=True))
    op.add_column('media_files', sa.Column('processing_time_ms', sa.Float(), nullable=True))
    op.add_column('media_files', sa.Column('media_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_files', 'media_type')
    op.drop_column('media_files', 'processing_time_ms')
    op.drop_column('media_files', 'matches_found')
    op.create_index(op.f('idx_media_embeddings_vector_hnsw'), 'media_embeddings', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
