# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: myso/rpc/alpha/event_service.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'myso/rpc/alpha/event_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from app.chain.proto.myso.rpc.v2 import event_pb2 as myso_dot_rpc_dot_v2_dot_event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"myso/rpc/alpha/event_service.proto\x12\x0emyso.rpc.alpha\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17myso/rpc/v2/event.proto\"\xc8\x01\n\x1eListAuthenticatedEventsRequest\x12\x16\n\tstream_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1d\n\x10start_checkpoint\x18\x02 \x01(\x04H\x01\x88\x01\x01\x12\x16\n\tpage_size\x18\x03 \x01(\rH\x02\x88\x01\x01\x12\x17\n\npage_token\x18\x04 \x01(\x0cH\x03\x88\x01\x01\x42\x0c\n\n_stream_idB\x13\n\x11_start_checkpointB\x0c\n\n_page_sizeB\r\n\x0b_page_token\"\xcf\x01\n\x1fListAuthenticatedEventsResponse\x12\x32\n\x06\x65vents\x18\x01 \x03(\x0b\x32\".myso.rpc.alpha.AuthenticatedEvent\x12\'\n\x1ahighest_indexed_checkpoint\x18\x02 \x01(\x04H\x00\x88\x01\x01\x12\x1c\n\x0fnext_page_token\x18\x03 \x01(\x0cH\x01\x88\x01\x01\x42\x1d\n\x1b_highest_indexed_checkpointB\x12\n\x10_next_page_token\"\xa6\x02\n\x12\x41uthenticatedEvent\x12\x17\n\ncheckpoint\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12 \n\x13\x61\x63\x63umulator_version\x18\x02 \x01(\x04H\x01\x88\x01\x01\x12\x1c\n\x0ftransaction_idx\x18\x03 \x01(\rH\x02\x88\x01\x01\x12\x16\n\tevent_idx\x18\x04 \x01(\rH\x03\x88\x01\x01\x12&\n\x05\x65vent\x18\x05 \x01(\x0b\x32\x12.myso.rpc.v2.EventH\x04\x88\x01\x01\x12\x16\n\tstream_id\x18\x06 \x01(\tH\x05\x88\x01\x01\x42\r\n\x0b_checkpointB\x16\n\x14_accumulator_versionB\x12\n\x10_transaction_idxB\x0c\n\n_event_idxB\x08\n\x06_eventB\x0c\n\n_stream_id2\x8a\x01\n\x0c\x45ventService\x12z\n\x17ListAuthenticatedEvents\x12..myso.rpc.alpha.ListAuthenticatedEventsRequest\x1a/.myso.rpc.alpha.ListAuthenticatedEventsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myso.rpc.alpha.event_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTAUTHENTICATEDEVENTSREQUEST']._serialized_start=109
  _globals['_LISTAUTHENTICATEDEVENTSREQUEST']._serialized_end=309
  _globals['_LISTAUTHENTICATEDEVENTSRESPONSE']._serialized_start=312
  _globals['_LISTAUTHENTICATEDEVENTSRESPONSE']._serialized_end=519
  _globals['_AUTHENTICATEDEVENT']._serialized_start=522
  _globals['_AUTHENTICATEDEVENT']._serialized_end=816
  _globals['_EVENTSERVICE']._serialized_start=819
  _globals['_EVENTSERVICE']._serialized_end=957
# @@protoc_insertion_point(module_scope)
