# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: myso/rpc/v2/argument.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'myso/rpc/v2/argument.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1amyso/rpc/v2/argument.proto\x12\x0bmyso.rpc.v2\"\xf9\x01\n\x08\x41rgument\x12\x35\n\x04kind\x18\x01 \x01(\x0e\x32\".myso.rpc.v2.Argument.ArgumentKindH\x00\x88\x01\x01\x12\x12\n\x05input\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x13\n\x06result\x18\x03 \x01(\rH\x02\x88\x01\x01\x12\x16\n\tsubresult\x18\x04 \x01(\rH\x03\x88\x01\x01\"I\n\x0c\x41rgumentKind\x12\x19\n\x15\x41RGUMENT_KIND_UNKNOWN\x10\x00\x12\x07\n\x03GAS\x10\x01\x12\t\n\x05INPUT\x10\x02\x12\n\n\x06RESULT\x10\x03\x42\x07\n\x05_kindB\x08\n\x06_inputB\t\n\x07_resultB\x0c\n\n_subresultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myso.rpc.v2.argument_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARGUMENT']._serialized_start=44
  _globals['_ARGUMENT']._serialized_end=293
  _globals['_ARGUMENT_ARGUMENTKIND']._serialized_start=176
  _globals['_ARGUMENT_ARGUMENTKIND']._serialized_end=249
# @@protoc_insertion_point(module_scope)
