# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: myso/rpc/v2/checkpoint.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'myso/rpc/v2/checkpoint.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.chain.proto.myso.rpc.v2 import checkpoint_contents_pb2 as myso_dot_rpc_dot_v2_dot_checkpoint__contents__pb2
from app.chain.proto.myso.rpc.v2 import checkpoint_summary_pb2 as myso_dot_rpc_dot_v2_dot_checkpoint__summary__pb2
from app.chain.proto.myso.rpc.v2 import executed_transaction_pb2 as myso_dot_rpc_dot_v2_dot_executed__transaction__pb2
from app.chain.proto.myso.rpc.v2 import object_pb2 as myso_dot_rpc_dot_v2_dot_object__pb2
from app.chain.proto.myso.rpc.v2 import signature_pb2 as myso_dot_rpc_dot_v2_dot_signature__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cmyso/rpc/v2/checkpoint.proto\x12\x0bmyso.rpc.v2\x1a%myso/rpc/v2/checkpoint_contents.proto\x1a$myso/rpc/v2/checkpoint_summary.proto\x1a&myso/rpc/v2/executed_transaction.proto\x1a\x18myso/rpc/v2/object.proto\x1a\x1bmyso/rpc/v2/signature.proto\"\xa8\x03\n\nCheckpoint\x12\x1c\n\x0fsequence_number\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x13\n\x06\x64igest\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x34\n\x07summary\x18\x03 \x01(\x0b\x32\x1e.myso.rpc.v2.CheckpointSummaryH\x02\x88\x01\x01\x12\x41\n\tsignature\x18\x04 \x01(\x0b\x32).myso.rpc.v2.ValidatorAggregatedSignatureH\x03\x88\x01\x01\x12\x36\n\x08\x63ontents\x18\x05 \x01(\x0b\x32\x1f.myso.rpc.v2.CheckpointContentsH\x04\x88\x01\x01\x12\x36\n\x0ctransactions\x18\x06 \x03(\x0b\x32 .myso.rpc.v2.ExecutedTransaction\x12,\n\x07objects\x18\x07 \x01(\x0b\x32\x16.myso.rpc.v2.ObjectSetH\x05\x88\x01\x01\x42\x12\n\x10_sequence_numberB\t\n\x07_digestB\n\n\x08_summaryB\x0c\n\n_signatureB\x0b\n\t_contentsB\n\n\x08_objectsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myso.rpc.v2.checkpoint_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKPOINT']._serialized_start=218
  _globals['_CHECKPOINT']._serialized_end=642
# @@protoc_insertion_point(module_scope)
