# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: myso/rpc/v2/checkpoint_contents.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'myso/rpc/v2/checkpoint_contents.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.chain.proto.myso.rpc.v2 import bcs_pb2 as myso_dot_rpc_dot_v2_dot_bcs__pb2
from app.chain.proto.myso.rpc.v2 import signature_pb2 as myso_dot_rpc_dot_v2_dot_signature__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%myso/rpc/v2/checkpoint_contents.proto\x12\x0bmyso.rpc.v2\x1a\x15myso/rpc/v2/bcs.proto\x1a\x1bmyso/rpc/v2/signature.proto\"\xc2\x01\n\x12\x43heckpointContents\x12\"\n\x03\x62\x63s\x18\x01 \x01(\x0b\x32\x10.myso.rpc.v2.BcsH\x00\x88\x01\x01\x12\x13\n\x06\x64igest\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x14\n\x07version\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12>\n\x0ctransactions\x18\x04 \x03(\x0b\x32(.myso.rpc.v2.CheckpointedTransactionInfoB\x06\n\x04_bcsB\t\n\x07_digestB\n\n\x08_version\"\xdf\x01\n\x1b\x43heckpointedTransactionInfo\x12\x18\n\x0btransaction\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07\x65\x66\x66\x65\x63ts\x18\x02 \x01(\tH\x01\x88\x01\x01\x12.\n\nsignatures\x18\x03 \x03(\x0b\x32\x1a.myso.rpc.v2.UserSignature\x12\x44\n\x18\x61\x64\x64ress_aliases_versions\x18\x04 \x03(\x0b\x32\".myso.rpc.v2.AddressAliasesVersionB\x0e\n\x0c_transactionB\n\n\x08_effects\"9\n\x15\x41\x64\x64ressAliasesVersion\x12\x14\n\x07version\x18\x01 \x01(\x04H\x00\x88\x01\x01\x42\n\n\x08_versionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myso.rpc.v2.checkpoint_contents_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKPOINTCONTENTS']._serialized_start=107
  _globals['_CHECKPOINTCONTENTS']._serialized_end=301
  _globals['_CHECKPOINTEDTRANSACTIONINFO']._serialized_start=304
  _globals['_CHECKPOINTEDTRANSACTIONINFO']._serialized_end=527
  _globals['_ADDRESSALIASESVERSION']._serialized_start=529
  _globals['_ADDRESSALIASESVERSION']._serialized_end=586
# @@protoc_insertion_point(module_scope)
