# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: myso/rpc/v2/epoch.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'myso/rpc/v2/epoch.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from app.chain.proto.myso.rpc.v2 import protocol_config_pb2 as myso_dot_rpc_dot_v2_dot_protocol__config__pb2
from app.chain.proto.myso.rpc.v2 import signature_pb2 as myso_dot_rpc_dot_v2_dot_signature__pb2
from app.chain.proto.myso.rpc.v2 import system_state_pb2 as myso_dot_rpc_dot_v2_dot_system__state__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17myso/rpc/v2/epoch.proto\x12\x0bmyso.rpc.v2\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!myso/rpc/v2/protocol_config.proto\x1a\x1bmyso/rpc/v2/signature.proto\x1a\x1emyso/rpc/v2/system_state.proto\"\x91\x04\n\x05\x45poch\x12\x12\n\x05\x65poch\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x37\n\tcommittee\x18\x02 \x01(\x0b\x32\x1f.myso.rpc.v2.ValidatorCommitteeH\x01\x88\x01\x01\x12\x33\n\x0csystem_state\x18\x03 \x01(\x0b\x32\x18.myso.rpc.v2.SystemStateH\x02\x88\x01\x01\x12\x1d\n\x10\x66irst_checkpoint\x18\x04 \x01(\x04H\x03\x88\x01\x01\x12\x1c\n\x0flast_checkpoint\x18\x05 \x01(\x04H\x04\x88\x01\x01\x12.\n\x05start\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x05\x88\x01\x01\x12,\n\x03\x65nd\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x06\x88\x01\x01\x12 \n\x13reference_gas_price\x18\x08 \x01(\x04H\x07\x88\x01\x01\x12\x39\n\x0fprotocol_config\x18\t \x01(\x0b\x32\x1b.myso.rpc.v2.ProtocolConfigH\x08\x88\x01\x01\x42\x08\n\x06_epochB\x0c\n\n_committeeB\x0f\n\r_system_stateB\x13\n\x11_first_checkpointB\x12\n\x10_last_checkpointB\x08\n\x06_startB\x06\n\x04_endB\x16\n\x14_reference_gas_priceB\x12\n\x10_protocol_configb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myso.rpc.v2.epoch_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EPOCH']._serialized_start=170
  _globals['_EPOCH']._serialized_end=699
# @@protoc_insertion_point(module_scope)
