# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: myso/rpc/v2/event.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'myso/rpc/v2/event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from app.chain.proto.myso.rpc.v2 import bcs_pb2 as myso_dot_rpc_dot_v2_dot_bcs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17myso/rpc/v2/event.proto\x12\x0bmyso.rpc.v2\x1a\x1cgoogle/protobuf/struct.proto\x1a\x15myso/rpc/v2/bcs.proto\"\x83\x01\n\x11TransactionEvents\x12\"\n\x03\x62\x63s\x18\x01 \x01(\x0b\x32\x10.myso.rpc.v2.BcsH\x00\x88\x01\x01\x12\x13\n\x06\x64igest\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\"\n\x06\x65vents\x18\x03 \x03(\x0b\x32\x12.myso.rpc.v2.EventB\x06\n\x04_bcsB\t\n\x07_digest\"\x81\x02\n\x05\x45vent\x12\x17\n\npackage_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06module\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x06sender\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x17\n\nevent_type\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\'\n\x08\x63ontents\x18\x05 \x01(\x0b\x32\x10.myso.rpc.v2.BcsH\x04\x88\x01\x01\x12)\n\x04json\x18\x06 \x01(\x0b\x32\x16.google.protobuf.ValueH\x05\x88\x01\x01\x42\r\n\x0b_package_idB\t\n\x07_moduleB\t\n\x07_senderB\r\n\x0b_event_typeB\x0b\n\t_contentsB\x07\n\x05_jsonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myso.rpc.v2.event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONEVENTS']._serialized_start=94
  _globals['_TRANSACTIONEVENTS']._serialized_end=225
  _globals['_EVENT']._serialized_start=228
  _globals['_EVENT']._serialized_end=485
# @@protoc_insertion_point(module_scope)
