# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: myso/rpc/v2/executed_transaction.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'myso/rpc/v2/executed_transaction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from app.chain.proto.myso.rpc.v2 import balance_change_pb2 as myso_dot_rpc_dot_v2_dot_balance__change__pb2
from app.chain.proto.myso.rpc.v2 import effects_pb2 as myso_dot_rpc_dot_v2_dot_effects__pb2
from app.chain.proto.myso.rpc.v2 import event_pb2 as myso_dot_rpc_dot_v2_dot_event__pb2
from app.chain.proto.myso.rpc.v2 import object_pb2 as myso_dot_rpc_dot_v2_dot_object__pb2
from app.chain.proto.myso.rpc.v2 import signature_pb2 as myso_dot_rpc_dot_v2_dot_signature__pb2
from app.chain.proto.myso.rpc.v2 import transaction_pb2 as myso_dot_rpc_dot_v2_dot_transaction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&myso/rpc/v2/executed_transaction.proto\x12\x0bmyso.rpc.v2\x1a\x1fgoogle/protobuf/timestamp.proto\x1a myso/rpc/v2/balance_change.proto\x1a\x19myso/rpc/v2/effects.proto\x1a\x17myso/rpc/v2/event.proto\x1a\x18myso/rpc/v2/object.proto\x1a\x1bmyso/rpc/v2/signature.proto\x1a\x1dmyso/rpc/v2/transaction.proto\"\x85\x04\n\x13\x45xecutedTransaction\x12\x13\n\x06\x64igest\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x32\n\x0btransaction\x18\x02 \x01(\x0b\x32\x18.myso.rpc.v2.TransactionH\x01\x88\x01\x01\x12.\n\nsignatures\x18\x03 \x03(\x0b\x32\x1a.myso.rpc.v2.UserSignature\x12\x35\n\x07\x65\x66\x66\x65\x63ts\x18\x04 \x01(\x0b\x32\x1f.myso.rpc.v2.TransactionEffectsH\x02\x88\x01\x01\x12\x33\n\x06\x65vents\x18\x05 \x01(\x0b\x32\x1e.myso.rpc.v2.TransactionEventsH\x03\x88\x01\x01\x12\x17\n\ncheckpoint\x18\x06 \x01(\x04H\x04\x88\x01\x01\x12\x32\n\ttimestamp\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x05\x88\x01\x01\x12\x33\n\x0f\x62\x61lance_changes\x18\x08 \x03(\x0b\x32\x1a.myso.rpc.v2.BalanceChange\x12,\n\x07objects\x18\t \x01(\x0b\x32\x16.myso.rpc.v2.ObjectSetH\x06\x88\x01\x01\x42\t\n\x07_digestB\x0e\n\x0c_transactionB\n\n\x08_effectsB\t\n\x07_eventsB\r\n\x0b_checkpointB\x0c\n\n_timestampB\n\n\x08_objectsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myso.rpc.v2.executed_transaction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXECUTEDTRANSACTION']._serialized_start=261
  _globals['_EXECUTEDTRANSACTION']._serialized_end=778
# @@protoc_insertion_point(module_scope)
