# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: myso/rpc/v2/gas_cost_summary.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'myso/rpc/v2/gas_cost_summary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"myso/rpc/v2/gas_cost_summary.proto\x12\x0bmyso.rpc.v2\"\xe8\x01\n\x0eGasCostSummary\x12\x1d\n\x10\x63omputation_cost\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x19\n\x0cstorage_cost\x18\x02 \x01(\x04H\x01\x88\x01\x01\x12\x1b\n\x0estorage_rebate\x18\x03 \x01(\x04H\x02\x88\x01\x01\x12\'\n\x1anon_refundable_storage_fee\x18\x04 \x01(\x04H\x03\x88\x01\x01\x42\x13\n\x11_computation_costB\x0f\n\r_storage_costB\x11\n\x0f_storage_rebateB\x1d\n\x1b_non_refundable_storage_feeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myso.rpc.v2.gas_cost_summary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GASCOSTSUMMARY']._serialized_start=52
  _globals['_GASCOSTSUMMARY']._serialized_end=284
# @@protoc_insertion_point(module_scope)
