# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: myso/rpc/v2/input.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'myso/rpc/v2/input.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17myso/rpc/v2/input.proto\x12\x0bmyso.rpc.v2\x1a\x1cgoogle/protobuf/struct.proto\"\x8e\x05\n\x05Input\x12/\n\x04kind\x18\x01 \x01(\x0e\x32\x1c.myso.rpc.v2.Input.InputKindH\x00\x88\x01\x01\x12\x11\n\x04pure\x18\x02 \x01(\x0cH\x01\x88\x01\x01\x12\x16\n\tobject_id\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x14\n\x07version\x18\x04 \x01(\x04H\x03\x88\x01\x01\x12\x13\n\x06\x64igest\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x14\n\x07mutable\x18\x06 \x01(\x08H\x05\x88\x01\x01\x12\x36\n\nmutability\x18\x07 \x01(\x0e\x32\x1d.myso.rpc.v2.Input.MutabilityH\x06\x88\x01\x01\x12;\n\x10\x66unds_withdrawal\x18\x08 \x01(\x0b\x32\x1c.myso.rpc.v2.FundsWithdrawalH\x07\x88\x01\x01\x12-\n\x07literal\x18\xe8\x07 \x01(\x0b\x32\x16.google.protobuf.ValueH\x08\x88\x01\x01\"v\n\tInputKind\x12\x16\n\x12INPUT_KIND_UNKNOWN\x10\x00\x12\x08\n\x04PURE\x10\x01\x12\x16\n\x12IMMUTABLE_OR_OWNED\x10\x02\x12\n\n\x06SHARED\x10\x03\x12\r\n\tRECEIVING\x10\x04\x12\x14\n\x10\x46UNDS_WITHDRAWAL\x10\x05\"Y\n\nMutability\x12\x16\n\x12MUTABILITY_UNKNOWN\x10\x00\x12\r\n\tIMMUTABLE\x10\x01\x12\x0b\n\x07MUTABLE\x10\x02\x12\x17\n\x13NON_EXCLUSIVE_WRITE\x10\x03\x42\x07\n\x05_kindB\x07\n\x05_pureB\x0c\n\n_object_idB\n\n\x08_versionB\t\n\x07_digestB\n\n\x08_mutableB\r\n\x0b_mutabilityB\x13\n\x11_funds_withdrawalB\n\n\x08_literal\"\xd3\x01\n\x0f\x46undsWithdrawal\x12\x13\n\x06\x61mount\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x16\n\tcoin_type\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x38\n\x06source\x18\x03 \x01(\x0e\x32#.myso.rpc.v2.FundsWithdrawal.SourceH\x02\x88\x01\x01\"5\n\x06Source\x12\x12\n\x0eSOURCE_UNKNOWN\x10\x00\x12\n\n\x06SENDER\x10\x01\x12\x0b\n\x07SPONSOR\x10\x02\x42\t\n\x07_amountB\x0c\n\n_coin_typeB\t\n\x07_sourceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myso.rpc.v2.input_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INPUT']._serialized_start=71
  _globals['_INPUT']._serialized_end=725
  _globals['_INPUT_INPUTKIND']._serialized_start=401
  _globals['_INPUT_INPUTKIND']._serialized_end=519
  _globals['_INPUT_MUTABILITY']._serialized_start=521
  _globals['_INPUT_MUTABILITY']._serialized_end=610
  _globals['_FUNDSWITHDRAWAL']._serialized_start=728
  _globals['_FUNDSWITHDRAWAL']._serialized_end=939
  _globals['_FUNDSWITHDRAWAL_SOURCE']._serialized_start=850
  _globals['_FUNDSWITHDRAWAL_SOURCE']._serialized_end=903
# @@protoc_insertion_point(module_scope)
