# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: myso/rpc/v2/jwk.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'myso/rpc/v2/jwk.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15myso/rpc/v2/jwk.proto\x12\x0bmyso.rpc.v2\";\n\x05JwkId\x12\x10\n\x03iss\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x10\n\x03kid\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x06\n\x04_issB\x06\n\x04_kid\"e\n\x03Jwk\x12\x10\n\x03kty\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0e\n\x01\x65\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x0e\n\x01n\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x10\n\x03\x61lg\x18\x04 \x01(\tH\x03\x88\x01\x01\x42\x06\n\x04_ktyB\x04\n\x02_eB\x04\n\x02_nB\x06\n\x04_algb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myso.rpc.v2.jwk_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JWKID']._serialized_start=38
  _globals['_JWKID']._serialized_end=97
  _globals['_JWK']._serialized_start=99
  _globals['_JWK']._serialized_end=200
# @@protoc_insertion_point(module_scope)
