# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.chain.proto.myso.rpc.v2 import ledger_service_pb2 as myso_dot_rpc_dot_v2_dot_ledger__service__pb2

GRPC_GENERATED_VERSION = '1.82.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in myso/rpc/v2/ledger_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LedgerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServiceInfo = channel.unary_unary(
                '/myso.rpc.v2.LedgerService/GetServiceInfo',
                request_serializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetServiceInfoRequest.SerializeToString,
                response_deserializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetServiceInfoResponse.FromString,
                _registered_method=True)
        self.GetObject = channel.unary_unary(
                '/myso.rpc.v2.LedgerService/GetObject',
                request_serializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetObjectRequest.SerializeToString,
                response_deserializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetObjectResponse.FromString,
                _registered_method=True)
        self.BatchGetObjects = channel.unary_unary(
                '/myso.rpc.v2.LedgerService/BatchGetObjects',
                request_serializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.BatchGetObjectsRequest.SerializeToString,
                response_deserializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.BatchGetObjectsResponse.FromString,
                _registered_method=True)
        self.GetTransaction = channel.unary_unary(
                '/myso.rpc.v2.LedgerService/GetTransaction',
                request_serializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetTransactionRequest.SerializeToString,
                response_deserializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetTransactionResponse.FromString,
                _registered_method=True)
        self.BatchGetTransactions = channel.unary_unary(
                '/myso.rpc.v2.LedgerService/BatchGetTransactions',
                request_serializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.BatchGetTransactionsRequest.SerializeToString,
                response_deserializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.BatchGetTransactionsResponse.FromString,
                _registered_method=True)
        self.GetCheckpoint = channel.unary_unary(
                '/myso.rpc.v2.LedgerService/GetCheckpoint',
                request_serializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetCheckpointRequest.SerializeToString,
                response_deserializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetCheckpointResponse.FromString,
                _registered_method=True)
        self.GetEpoch = channel.unary_unary(
                '/myso.rpc.v2.LedgerService/GetEpoch',
                request_serializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetEpochRequest.SerializeToString,
                response_deserializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetEpochResponse.FromString,
                _registered_method=True)


class LedgerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetServiceInfo(self, request, context):
        """Query the service for general information about its current state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchGetObjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchGetTransactions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEpoch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LedgerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetServiceInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceInfo,
                    request_deserializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetServiceInfoRequest.FromString,
                    response_serializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetServiceInfoResponse.SerializeToString,
            ),
            'GetObject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObject,
                    request_deserializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetObjectRequest.FromString,
                    response_serializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetObjectResponse.SerializeToString,
            ),
            'BatchGetObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGetObjects,
                    request_deserializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.BatchGetObjectsRequest.FromString,
                    response_serializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.BatchGetObjectsResponse.SerializeToString,
            ),
            'GetTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransaction,
                    request_deserializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetTransactionRequest.FromString,
                    response_serializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetTransactionResponse.SerializeToString,
            ),
            'BatchGetTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGetTransactions,
                    request_deserializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.BatchGetTransactionsRequest.FromString,
                    response_serializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.BatchGetTransactionsResponse.SerializeToString,
            ),
            'GetCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCheckpoint,
                    request_deserializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetCheckpointRequest.FromString,
                    response_serializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetCheckpointResponse.SerializeToString,
            ),
            'GetEpoch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEpoch,
                    request_deserializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetEpochRequest.FromString,
                    response_serializer=myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetEpochResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myso.rpc.v2.LedgerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('myso.rpc.v2.LedgerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LedgerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetServiceInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myso.rpc.v2.LedgerService/GetServiceInfo',
            myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetServiceInfoRequest.SerializeToString,
            myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetServiceInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myso.rpc.v2.LedgerService/GetObject',
            myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetObjectRequest.SerializeToString,
            myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchGetObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myso.rpc.v2.LedgerService/BatchGetObjects',
            myso_dot_rpc_dot_v2_dot_ledger__service__pb2.BatchGetObjectsRequest.SerializeToString,
            myso_dot_rpc_dot_v2_dot_ledger__service__pb2.BatchGetObjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myso.rpc.v2.LedgerService/GetTransaction',
            myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetTransactionRequest.SerializeToString,
            myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchGetTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myso.rpc.v2.LedgerService/BatchGetTransactions',
            myso_dot_rpc_dot_v2_dot_ledger__service__pb2.BatchGetTransactionsRequest.SerializeToString,
            myso_dot_rpc_dot_v2_dot_ledger__service__pb2.BatchGetTransactionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myso.rpc.v2.LedgerService/GetCheckpoint',
            myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetCheckpointRequest.SerializeToString,
            myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEpoch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myso.rpc.v2.LedgerService/GetEpoch',
            myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetEpochRequest.SerializeToString,
            myso_dot_rpc_dot_v2_dot_ledger__service__pb2.GetEpochResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
