# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.chain.proto.myso.rpc.v2 import move_package_service_pb2 as myso_dot_rpc_dot_v2_dot_move__package__service__pb2

GRPC_GENERATED_VERSION = '1.82.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in myso/rpc/v2/move_package_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MovePackageServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPackage = channel.unary_unary(
                '/myso.rpc.v2.MovePackageService/GetPackage',
                request_serializer=myso_dot_rpc_dot_v2_dot_move__package__service__pb2.GetPackageRequest.SerializeToString,
                response_deserializer=myso_dot_rpc_dot_v2_dot_move__package__service__pb2.GetPackageResponse.FromString,
                _registered_method=True)
        self.GetDatatype = channel.unary_unary(
                '/myso.rpc.v2.MovePackageService/GetDatatype',
                request_serializer=myso_dot_rpc_dot_v2_dot_move__package__service__pb2.GetDatatypeRequest.SerializeToString,
                response_deserializer=myso_dot_rpc_dot_v2_dot_move__package__service__pb2.GetDatatypeResponse.FromString,
                _registered_method=True)
        self.GetFunction = channel.unary_unary(
                '/myso.rpc.v2.MovePackageService/GetFunction',
                request_serializer=myso_dot_rpc_dot_v2_dot_move__package__service__pb2.GetFunctionRequest.SerializeToString,
                response_deserializer=myso_dot_rpc_dot_v2_dot_move__package__service__pb2.GetFunctionResponse.FromString,
                _registered_method=True)
        self.ListPackageVersions = channel.unary_unary(
                '/myso.rpc.v2.MovePackageService/ListPackageVersions',
                request_serializer=myso_dot_rpc_dot_v2_dot_move__package__service__pb2.ListPackageVersionsRequest.SerializeToString,
                response_deserializer=myso_dot_rpc_dot_v2_dot_move__package__service__pb2.ListPackageVersionsResponse.FromString,
                _registered_method=True)


class MovePackageServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetPackage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDatatype(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFunction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPackageVersions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MovePackageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPackage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPackage,
                    request_deserializer=myso_dot_rpc_dot_v2_dot_move__package__service__pb2.GetPackageRequest.FromString,
                    response_serializer=myso_dot_rpc_dot_v2_dot_move__package__service__pb2.GetPackageResponse.SerializeToString,
            ),
            'GetDatatype': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDatatype,
                    request_deserializer=myso_dot_rpc_dot_v2_dot_move__package__service__pb2.GetDatatypeRequest.FromString,
                    response_serializer=myso_dot_rpc_dot_v2_dot_move__package__service__pb2.GetDatatypeResponse.SerializeToString,
            ),
            'GetFunction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFunction,
                    request_deserializer=myso_dot_rpc_dot_v2_dot_move__package__service__pb2.GetFunctionRequest.FromString,
                    response_serializer=myso_dot_rpc_dot_v2_dot_move__package__service__pb2.GetFunctionResponse.SerializeToString,
            ),
            'ListPackageVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPackageVersions,
                    request_deserializer=myso_dot_rpc_dot_v2_dot_move__package__service__pb2.ListPackageVersionsRequest.FromString,
                    response_serializer=myso_dot_rpc_dot_v2_dot_move__package__service__pb2.ListPackageVersionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myso.rpc.v2.MovePackageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('myso.rpc.v2.MovePackageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MovePackageService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myso.rpc.v2.MovePackageService/GetPackage',
            myso_dot_rpc_dot_v2_dot_move__package__service__pb2.GetPackageRequest.SerializeToString,
            myso_dot_rpc_dot_v2_dot_move__package__service__pb2.GetPackageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDatatype(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myso.rpc.v2.MovePackageService/GetDatatype',
            myso_dot_rpc_dot_v2_dot_move__package__service__pb2.GetDatatypeRequest.SerializeToString,
            myso_dot_rpc_dot_v2_dot_move__package__service__pb2.GetDatatypeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFunction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myso.rpc.v2.MovePackageService/GetFunction',
            myso_dot_rpc_dot_v2_dot_move__package__service__pb2.GetFunctionRequest.SerializeToString,
            myso_dot_rpc_dot_v2_dot_move__package__service__pb2.GetFunctionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPackageVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myso.rpc.v2.MovePackageService/ListPackageVersions',
            myso_dot_rpc_dot_v2_dot_move__package__service__pb2.ListPackageVersionsRequest.SerializeToString,
            myso_dot_rpc_dot_v2_dot_move__package__service__pb2.ListPackageVersionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
