# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: myso/rpc/v2/name_service.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'myso/rpc/v2/name_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1emyso/rpc/v2/name_service.proto\x12\x0bmyso.rpc.v2\x1a\x1fgoogle/protobuf/timestamp.proto\"/\n\x11LookupNameRequest\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_name\"M\n\x12LookupNameResponse\x12,\n\x06record\x18\x01 \x01(\x0b\x32\x17.myso.rpc.v2.NameRecordH\x00\x88\x01\x01\x42\t\n\x07_record\"<\n\x18ReverseLookupNameRequest\x12\x14\n\x07\x61\x64\x64ress\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_address\"T\n\x19ReverseLookupNameResponse\x12,\n\x06record\x18\x01 \x01(\x0b\x32\x17.myso.rpc.v2.NameRecordH\x00\x88\x01\x01\x42\t\n\x07_record\"\xe0\x02\n\nNameRecord\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12 \n\x13registration_nft_id\x18\x03 \x01(\tH\x02\x88\x01\x01\x12=\n\x14\x65xpiration_timestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x03\x88\x01\x01\x12\x1b\n\x0etarget_address\x18\x05 \x01(\tH\x04\x88\x01\x01\x12/\n\x04\x64\x61ta\x18\x06 \x03(\x0b\x32!.myso.rpc.v2.NameRecord.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x05\n\x03_idB\x07\n\x05_nameB\x16\n\x14_registration_nft_idB\x17\n\x15_expiration_timestampB\x11\n\x0f_target_address2\xc0\x01\n\x0bNameService\x12M\n\nLookupName\x12\x1e.myso.rpc.v2.LookupNameRequest\x1a\x1f.myso.rpc.v2.LookupNameResponse\x12\x62\n\x11ReverseLookupName\x12%.myso.rpc.v2.ReverseLookupNameRequest\x1a&.myso.rpc.v2.ReverseLookupNameResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myso.rpc.v2.name_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NAMERECORD_DATAENTRY']._loaded_options = None
  _globals['_NAMERECORD_DATAENTRY']._serialized_options = b'8\001'
  _globals['_LOOKUPNAMEREQUEST']._serialized_start=80
  _globals['_LOOKUPNAMEREQUEST']._serialized_end=127
  _globals['_LOOKUPNAMERESPONSE']._serialized_start=129
  _globals['_LOOKUPNAMERESPONSE']._serialized_end=206
  _globals['_REVERSELOOKUPNAMEREQUEST']._serialized_start=208
  _globals['_REVERSELOOKUPNAMEREQUEST']._serialized_end=268
  _globals['_REVERSELOOKUPNAMERESPONSE']._serialized_start=270
  _globals['_REVERSELOOKUPNAMERESPONSE']._serialized_end=354
  _globals['_NAMERECORD']._serialized_start=357
  _globals['_NAMERECORD']._serialized_end=709
  _globals['_NAMERECORD_DATAENTRY']._serialized_start=582
  _globals['_NAMERECORD_DATAENTRY']._serialized_end=625
  _globals['_NAMESERVICE']._serialized_start=712
  _globals['_NAMESERVICE']._serialized_end=904
# @@protoc_insertion_point(module_scope)
