# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: myso/rpc/v2/object.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'myso/rpc/v2/object.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from app.chain.proto.myso.rpc.v2 import bcs_pb2 as myso_dot_rpc_dot_v2_dot_bcs__pb2
from app.chain.proto.myso.rpc.v2 import move_package_pb2 as myso_dot_rpc_dot_v2_dot_move__package__pb2
from app.chain.proto.myso.rpc.v2 import owner_pb2 as myso_dot_rpc_dot_v2_dot_owner__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18myso/rpc/v2/object.proto\x12\x0bmyso.rpc.v2\x1a\x1cgoogle/protobuf/struct.proto\x1a\x15myso/rpc/v2/bcs.proto\x1a\x1emyso/rpc/v2/move_package.proto\x1a\x17myso/rpc/v2/owner.proto\"\xe2\x04\n\x06Object\x12\"\n\x03\x62\x63s\x18\x01 \x01(\x0b\x32\x10.myso.rpc.v2.BcsH\x00\x88\x01\x01\x12\x16\n\tobject_id\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x14\n\x07version\x18\x03 \x01(\x04H\x02\x88\x01\x01\x12\x13\n\x06\x64igest\x18\x04 \x01(\tH\x03\x88\x01\x01\x12&\n\x05owner\x18\x05 \x01(\x0b\x32\x12.myso.rpc.v2.OwnerH\x04\x88\x01\x01\x12\x18\n\x0bobject_type\x18\x06 \x01(\tH\x05\x88\x01\x01\x12 \n\x13has_public_transfer\x18\x07 \x01(\x08H\x06\x88\x01\x01\x12\'\n\x08\x63ontents\x18\x08 \x01(\x0b\x32\x10.myso.rpc.v2.BcsH\x07\x88\x01\x01\x12*\n\x07package\x18\t \x01(\x0b\x32\x14.myso.rpc.v2.PackageH\x08\x88\x01\x01\x12!\n\x14previous_transaction\x18\n \x01(\tH\t\x88\x01\x01\x12\x1b\n\x0estorage_rebate\x18\x0b \x01(\x04H\n\x88\x01\x01\x12)\n\x04json\x18\x64 \x01(\x0b\x32\x16.google.protobuf.ValueH\x0b\x88\x01\x01\x12\x14\n\x07\x62\x61lance\x18\x65 \x01(\x04H\x0c\x88\x01\x01\x42\x06\n\x04_bcsB\x0c\n\n_object_idB\n\n\x08_versionB\t\n\x07_digestB\x08\n\x06_ownerB\x0e\n\x0c_object_typeB\x16\n\x14_has_public_transferB\x0b\n\t_contentsB\n\n\x08_packageB\x17\n\x15_previous_transactionB\x11\n\x0f_storage_rebateB\x07\n\x05_jsonB\n\n\x08_balance\"1\n\tObjectSet\x12$\n\x07objects\x18\x01 \x03(\x0b\x32\x13.myso.rpc.v2.Objectb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myso.rpc.v2.object_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBJECT']._serialized_start=152
  _globals['_OBJECT']._serialized_end=762
  _globals['_OBJECTSET']._serialized_start=764
  _globals['_OBJECTSET']._serialized_end=813
# @@protoc_insertion_point(module_scope)
