# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: myso/rpc/v2/owner.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'myso/rpc/v2/owner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17myso/rpc/v2/owner.proto\x12\x0bmyso.rpc.v2\"\xf5\x01\n\x05Owner\x12/\n\x04kind\x18\x01 \x01(\x0e\x32\x1c.myso.rpc.v2.Owner.OwnerKindH\x00\x88\x01\x01\x12\x14\n\x07\x61\x64\x64ress\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x14\n\x07version\x18\x03 \x01(\x04H\x02\x88\x01\x01\"n\n\tOwnerKind\x12\x16\n\x12OWNER_KIND_UNKNOWN\x10\x00\x12\x0b\n\x07\x41\x44\x44RESS\x10\x01\x12\n\n\x06OBJECT\x10\x02\x12\n\n\x06SHARED\x10\x03\x12\r\n\tIMMUTABLE\x10\x04\x12\x15\n\x11\x43ONSENSUS_ADDRESS\x10\x05\x42\x07\n\x05_kindB\n\n\x08_addressB\n\n\x08_versionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myso.rpc.v2.owner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OWNER']._serialized_start=41
  _globals['_OWNER']._serialized_end=286
  _globals['_OWNER_OWNERKIND']._serialized_start=143
  _globals['_OWNER_OWNERKIND']._serialized_end=253
# @@protoc_insertion_point(module_scope)
