# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.chain.proto.myso.rpc.v2 import signature_verification_service_pb2 as myso_dot_rpc_dot_v2_dot_signature__verification__service__pb2

GRPC_GENERATED_VERSION = '1.82.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in myso/rpc/v2/signature_verification_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SignatureVerificationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerifySignature = channel.unary_unary(
                '/myso.rpc.v2.SignatureVerificationService/VerifySignature',
                request_serializer=myso_dot_rpc_dot_v2_dot_signature__verification__service__pb2.VerifySignatureRequest.SerializeToString,
                response_deserializer=myso_dot_rpc_dot_v2_dot_signature__verification__service__pb2.VerifySignatureResponse.FromString,
                _registered_method=True)


class SignatureVerificationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def VerifySignature(self, request, context):
        """Perform signature verification of a UserSignature against the provided message.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SignatureVerificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerifySignature': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifySignature,
                    request_deserializer=myso_dot_rpc_dot_v2_dot_signature__verification__service__pb2.VerifySignatureRequest.FromString,
                    response_serializer=myso_dot_rpc_dot_v2_dot_signature__verification__service__pb2.VerifySignatureResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myso.rpc.v2.SignatureVerificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('myso.rpc.v2.SignatureVerificationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SignatureVerificationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VerifySignature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myso.rpc.v2.SignatureVerificationService/VerifySignature',
            myso_dot_rpc_dot_v2_dot_signature__verification__service__pb2.VerifySignatureRequest.SerializeToString,
            myso_dot_rpc_dot_v2_dot_signature__verification__service__pb2.VerifySignatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
