# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: myso/rpc/v2/signature_verification_service.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'myso/rpc/v2/signature_verification_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.chain.proto.myso.rpc.v2 import bcs_pb2 as myso_dot_rpc_dot_v2_dot_bcs__pb2
from app.chain.proto.myso.rpc.v2 import signature_pb2 as myso_dot_rpc_dot_v2_dot_signature__pb2
from app.chain.proto.myso.rpc.v2 import transaction_pb2 as myso_dot_rpc_dot_v2_dot_transaction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0myso/rpc/v2/signature_verification_service.proto\x12\x0bmyso.rpc.v2\x1a\x15myso/rpc/v2/bcs.proto\x1a\x1bmyso/rpc/v2/signature.proto\x1a\x1dmyso/rpc/v2/transaction.proto\"\xd6\x01\n\x16VerifySignatureRequest\x12&\n\x07message\x18\x01 \x01(\x0b\x32\x10.myso.rpc.v2.BcsH\x00\x88\x01\x01\x12\x32\n\tsignature\x18\x02 \x01(\x0b\x32\x1a.myso.rpc.v2.UserSignatureH\x01\x88\x01\x01\x12\x14\n\x07\x61\x64\x64ress\x18\x03 \x01(\tH\x02\x88\x01\x01\x12$\n\x04jwks\x18\x04 \x03(\x0b\x32\x16.myso.rpc.v2.ActiveJwkB\n\n\x08_messageB\x0c\n\n_signatureB\n\n\x08_address\"]\n\x17VerifySignatureResponse\x12\x15\n\x08is_valid\x18\x01 \x01(\x08H\x00\x88\x01\x01\x12\x13\n\x06reason\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x0b\n\t_is_validB\t\n\x07_reason2|\n\x1cSignatureVerificationService\x12\\\n\x0fVerifySignature\x12#.myso.rpc.v2.VerifySignatureRequest\x1a$.myso.rpc.v2.VerifySignatureResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myso.rpc.v2.signature_verification_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERIFYSIGNATUREREQUEST']._serialized_start=149
  _globals['_VERIFYSIGNATUREREQUEST']._serialized_end=363
  _globals['_VERIFYSIGNATURERESPONSE']._serialized_start=365
  _globals['_VERIFYSIGNATURERESPONSE']._serialized_end=458
  _globals['_SIGNATUREVERIFICATIONSERVICE']._serialized_start=460
  _globals['_SIGNATUREVERIFICATIONSERVICE']._serialized_end=584
# @@protoc_insertion_point(module_scope)
