# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.chain.proto.myso.rpc.v2 import state_service_pb2 as myso_dot_rpc_dot_v2_dot_state__service__pb2

GRPC_GENERATED_VERSION = '1.82.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in myso/rpc/v2/state_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StateServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDynamicFields = channel.unary_unary(
                '/myso.rpc.v2.StateService/ListDynamicFields',
                request_serializer=myso_dot_rpc_dot_v2_dot_state__service__pb2.ListDynamicFieldsRequest.SerializeToString,
                response_deserializer=myso_dot_rpc_dot_v2_dot_state__service__pb2.ListDynamicFieldsResponse.FromString,
                _registered_method=True)
        self.ListOwnedObjects = channel.unary_unary(
                '/myso.rpc.v2.StateService/ListOwnedObjects',
                request_serializer=myso_dot_rpc_dot_v2_dot_state__service__pb2.ListOwnedObjectsRequest.SerializeToString,
                response_deserializer=myso_dot_rpc_dot_v2_dot_state__service__pb2.ListOwnedObjectsResponse.FromString,
                _registered_method=True)
        self.GetCoinInfo = channel.unary_unary(
                '/myso.rpc.v2.StateService/GetCoinInfo',
                request_serializer=myso_dot_rpc_dot_v2_dot_state__service__pb2.GetCoinInfoRequest.SerializeToString,
                response_deserializer=myso_dot_rpc_dot_v2_dot_state__service__pb2.GetCoinInfoResponse.FromString,
                _registered_method=True)
        self.GetBalance = channel.unary_unary(
                '/myso.rpc.v2.StateService/GetBalance',
                request_serializer=myso_dot_rpc_dot_v2_dot_state__service__pb2.GetBalanceRequest.SerializeToString,
                response_deserializer=myso_dot_rpc_dot_v2_dot_state__service__pb2.GetBalanceResponse.FromString,
                _registered_method=True)
        self.ListBalances = channel.unary_unary(
                '/myso.rpc.v2.StateService/ListBalances',
                request_serializer=myso_dot_rpc_dot_v2_dot_state__service__pb2.ListBalancesRequest.SerializeToString,
                response_deserializer=myso_dot_rpc_dot_v2_dot_state__service__pb2.ListBalancesResponse.FromString,
                _registered_method=True)


class StateServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListDynamicFields(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOwnedObjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCoinInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBalances(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListDynamicFields': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDynamicFields,
                    request_deserializer=myso_dot_rpc_dot_v2_dot_state__service__pb2.ListDynamicFieldsRequest.FromString,
                    response_serializer=myso_dot_rpc_dot_v2_dot_state__service__pb2.ListDynamicFieldsResponse.SerializeToString,
            ),
            'ListOwnedObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOwnedObjects,
                    request_deserializer=myso_dot_rpc_dot_v2_dot_state__service__pb2.ListOwnedObjectsRequest.FromString,
                    response_serializer=myso_dot_rpc_dot_v2_dot_state__service__pb2.ListOwnedObjectsResponse.SerializeToString,
            ),
            'GetCoinInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCoinInfo,
                    request_deserializer=myso_dot_rpc_dot_v2_dot_state__service__pb2.GetCoinInfoRequest.FromString,
                    response_serializer=myso_dot_rpc_dot_v2_dot_state__service__pb2.GetCoinInfoResponse.SerializeToString,
            ),
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=myso_dot_rpc_dot_v2_dot_state__service__pb2.GetBalanceRequest.FromString,
                    response_serializer=myso_dot_rpc_dot_v2_dot_state__service__pb2.GetBalanceResponse.SerializeToString,
            ),
            'ListBalances': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBalances,
                    request_deserializer=myso_dot_rpc_dot_v2_dot_state__service__pb2.ListBalancesRequest.FromString,
                    response_serializer=myso_dot_rpc_dot_v2_dot_state__service__pb2.ListBalancesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myso.rpc.v2.StateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('myso.rpc.v2.StateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StateService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListDynamicFields(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myso.rpc.v2.StateService/ListDynamicFields',
            myso_dot_rpc_dot_v2_dot_state__service__pb2.ListDynamicFieldsRequest.SerializeToString,
            myso_dot_rpc_dot_v2_dot_state__service__pb2.ListDynamicFieldsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOwnedObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myso.rpc.v2.StateService/ListOwnedObjects',
            myso_dot_rpc_dot_v2_dot_state__service__pb2.ListOwnedObjectsRequest.SerializeToString,
            myso_dot_rpc_dot_v2_dot_state__service__pb2.ListOwnedObjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCoinInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myso.rpc.v2.StateService/GetCoinInfo',
            myso_dot_rpc_dot_v2_dot_state__service__pb2.GetCoinInfoRequest.SerializeToString,
            myso_dot_rpc_dot_v2_dot_state__service__pb2.GetCoinInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myso.rpc.v2.StateService/GetBalance',
            myso_dot_rpc_dot_v2_dot_state__service__pb2.GetBalanceRequest.SerializeToString,
            myso_dot_rpc_dot_v2_dot_state__service__pb2.GetBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBalances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myso.rpc.v2.StateService/ListBalances',
            myso_dot_rpc_dot_v2_dot_state__service__pb2.ListBalancesRequest.SerializeToString,
            myso_dot_rpc_dot_v2_dot_state__service__pb2.ListBalancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
