# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: myso/rpc/v2/subscription_service.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'myso/rpc/v2/subscription_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from app.chain.proto.myso.rpc.v2 import checkpoint_pb2 as myso_dot_rpc_dot_v2_dot_checkpoint__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&myso/rpc/v2/subscription_service.proto\x12\x0bmyso.rpc.v2\x1a google/protobuf/field_mask.proto\x1a\x1cmyso/rpc/v2/checkpoint.proto\"_\n\x1bSubscribeCheckpointsRequest\x12\x32\n\tread_mask\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.FieldMaskH\x00\x88\x01\x01\x42\x0c\n\n_read_mask\"\x7f\n\x1cSubscribeCheckpointsResponse\x12\x13\n\x06\x63ursor\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x30\n\ncheckpoint\x18\x02 \x01(\x0b\x32\x17.myso.rpc.v2.CheckpointH\x01\x88\x01\x01\x42\t\n\x07_cursorB\r\n\x0b_checkpoint2\x84\x01\n\x13SubscriptionService\x12m\n\x14SubscribeCheckpoints\x12(.myso.rpc.v2.SubscribeCheckpointsRequest\x1a).myso.rpc.v2.SubscribeCheckpointsResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myso.rpc.v2.subscription_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIBECHECKPOINTSREQUEST']._serialized_start=119
  _globals['_SUBSCRIBECHECKPOINTSREQUEST']._serialized_end=214
  _globals['_SUBSCRIBECHECKPOINTSRESPONSE']._serialized_start=216
  _globals['_SUBSCRIBECHECKPOINTSRESPONSE']._serialized_end=343
  _globals['_SUBSCRIPTIONSERVICE']._serialized_start=346
  _globals['_SUBSCRIPTIONSERVICE']._serialized_end=478
# @@protoc_insertion_point(module_scope)
