# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.chain.proto.myso.rpc.v2 import subscription_service_pb2 as myso_dot_rpc_dot_v2_dot_subscription__service__pb2

GRPC_GENERATED_VERSION = '1.82.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in myso/rpc/v2/subscription_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SubscriptionServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeCheckpoints = channel.unary_stream(
                '/myso.rpc.v2.SubscriptionService/SubscribeCheckpoints',
                request_serializer=myso_dot_rpc_dot_v2_dot_subscription__service__pb2.SubscribeCheckpointsRequest.SerializeToString,
                response_deserializer=myso_dot_rpc_dot_v2_dot_subscription__service__pb2.SubscribeCheckpointsResponse.FromString,
                _registered_method=True)


class SubscriptionServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def SubscribeCheckpoints(self, request, context):
        """Subscribe to the stream of checkpoints.

        This API provides a subscription to the checkpoint stream for the MySocial
        blockchain. When a subscription is initialized the stream will begin with
        the latest executed checkpoint as seen by the server. Responses are
        guaranteed to return checkpoints in-order and without gaps. This enables
        clients to know exactly the last checkpoint they have processed and in the
        event the subscription terminates (either by the client/server or by the
        connection breaking), clients will be able to reinitialize a subscription
        and then leverage other APIs in order to request data for the checkpoints
        they missed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SubscriptionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeCheckpoints': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeCheckpoints,
                    request_deserializer=myso_dot_rpc_dot_v2_dot_subscription__service__pb2.SubscribeCheckpointsRequest.FromString,
                    response_serializer=myso_dot_rpc_dot_v2_dot_subscription__service__pb2.SubscribeCheckpointsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myso.rpc.v2.SubscriptionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('myso.rpc.v2.SubscriptionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SubscriptionService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribeCheckpoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/myso.rpc.v2.SubscriptionService/SubscribeCheckpoints',
            myso_dot_rpc_dot_v2_dot_subscription__service__pb2.SubscribeCheckpointsRequest.SerializeToString,
            myso_dot_rpc_dot_v2_dot_subscription__service__pb2.SubscribeCheckpointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
